blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.list_view, name='blog'),
    path('<pk>/<title>/', views.post_view, name='blog-detail'),
    path('category/<pk>/<title>/', views.category_view, name='category-view'),
    path('tag/<pk>/<name>/', views.tag_view, name='tag-view'),
    path('search/', views.search, name='search-result'),
]

blog/models.py
from autoslug.fields import AutoSlugField
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.html import strip_tags
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class Service(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = 'service'
        verbose_name_plural = 'services'


class Category(models.Model):
    title = models.CharField(max_length=255, blank=False)
    slug = AutoSlugField(populate_from='title',
                         unique=False, primary_key=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category-view', kwargs={'pk': self.pk, 'title': self.slug})


class Tag(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tag-view', kwargs={'pk': self.pk, 'name': self.name})


class Post(models.Model):
    author = models.ForeignKey(
        User, blank=True, null=True, on_delete=models.SET_NULL, related_name='posts')
    title = models.CharField(max_length=255, blank=False, null=False)
    slug = AutoSlugField(_('slug'), populate_from='title',
                         unique=True, primary_key=False)
    category = models.ForeignKey(
        Category, blank=True, null=True, on_delete=models.SET_NULL, related_name='posts')
    content = RichTextUploadingField(_('content'), blank=True, null=True)
    summary = models.TextField(blank=True, null=True)
    published = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    published_date = models.DateField(
        auto_now_add=False, blank=True, null=True)
    tags = models.ManyToManyField(
        Tag, blank=True, related_name="posts")
    thumbnail = models.ImageField(
        upload_to='blog', blank=True, null=True, default='/blog/default.jpg')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog-detail', kwargs={'pk': self.pk, 'title': self.slug})

    def save(self, *args, **kwargs):
        if self.published and not self.published_date:
            self.published_date = timezone.now()
        if not self.published and self.published_date is not None:
            self.published_date = None
        if not self.summary and self.content:
            text = strip_tags(self.content)
            if len(text) > 200:
                text = '%s ...' % text[:200]
            self.summary = text
        super().save(*args, **kwargs)


class Comment(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    email = models.EmailField(max_length=255, blank=False, null=False)
    body = models.TextField(blank=False, null="False")
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, null=False, blank=False, related_name='comments')
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.name


class SearchTerms(models.Model):
    term = models.CharField(max_length=255, blank=False, null=False)
    slug = AutoSlugField(_('slug'), populate_from='term')

    def __str__(self):
        return self.term[:20]

    def slug_term(self):
        slug = self.term.replace(" ", "+")
        return slug

    def get_absolute_url(self):
        return "/blog/search/?q=%s" % self.term

blog/forms.py
from django import forms

from .models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        widgets = {
            'body': forms.Textarea()
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'category', 'content',
                  'summary', 'tags']

blog/views.py
from django.contrib import messages
from .forms import CommentForm
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView, View
from django.db.models import Q
from .models import Post, Category, Tag
from .models import SearchTerms


class BlogListView(View):
    def get(self, *args, **kwargs):
        context = {
            'posts': Post.objects.filter(published=True).order_by('-published_date'),
            'tags': Tag.objects.all,
            'categories': Category.objects.all(),
            'tags': Tag.objects.all()
        }
        return render(self.request, 'blog/blog.html', context)


list_view = BlogListView.as_view()


def post_view(request, pk, title):
    post = get_object_or_404(Post, pk=pk)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    posts = Post.objects.filter(published=True, category=post.category)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        context = {
            'post': post,
            'categories': categories,
            'tags': tags,
            'posts': posts
        }
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            n = {'new_comment': comment}
            context.update(n)
            messages.success(request, 'Thank you for the comment')
            return render(request, 'blog/detail.html', context)
        messages.error(request, 'Error in form')
        return render(request, 'blog/detail.html', context)

    context = {
        'form': CommentForm(),
        'post': post,
        'categories': categories,
        'tags': tags,
        'posts': posts
    }
    for cat in categories:
        print(cat.posts.count())
    return render(request, 'blog/detail.html', context)


class DetailView(DetailView):
    template_name = 'blog/detail.html'
    model = Post
    context_object_name = 'post'


def category_view(request, pk, *args, **kwargs):
    cat = get_object_or_404(Category, pk=pk)
    posts = Post.objects.filter(published=True, category=cat)
    context = {
        'posts': posts,
        'category': cat,
        'categories': Category.objects.all(),
        'tags': Tag.objects.all()
    }
    return render(request, 'blog/categories.html', context)


def tag_view(request, pk, *args, **kwargs):
    tag = get_object_or_404(Tag, pk=pk)
    posts = tag.posts.filter(published=True)
    cats = Category.objects.all()
    context = {'posts': posts,
               'tag': tag,
               'tags': Tag.objects.all(),
               'categories': cats}
    return render(request, 'blog/tag.html', context)


def search(request, *args, **kwargs):
    query_set = Post.objects.filter(published=True)
    query = request.GET.get('q')
    categories = Category.objects.all()
    if query:
        queryset = query_set.filter(
            Q(title__icontains=query) | Q(content__icontains=query) | Q(tags__name__icontains=query) | Q(category__title__icontains=query) | Q(author__first_name__icontains=query)).distinct()
    else:
        messages.error(request, "Type a valid term")
        return redirect('blog')
    context = {
        'posts': queryset,
        'query': query,
        'categories': categories
    }
    terms = SearchTerms.objects.filter(Q(term__icontains=query))
    if terms:
        t = {'terms': terms}
        context.update(t)
    else:
        term = SearchTerms(term=query)
        term.save()
    return render(request, 'blog/search.html', context)

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- SEO Meta Tags -->
    <meta name="description"
        content="Create a stylish landing page for your business startup and get leads for the offered services with this HTML landing page template.">
    <meta name="author" content="Inovatik">

    <!-- OG Meta Tags to improve the way the post looks when you share the page on LinkedIn, Facebook, Google+ -->
    <meta property="og:site_name" content="Feyton Inc" /> <!-- website name -->
    <meta property="og:site" content="https://www.feyton.co.rw" /> <!-- website link -->
    
    <meta property="og:title" content="{% block desc %}Feyton Inc{% endblock desc %}" /> <!-- title shown in the actual shared post -->
    <meta property="og:description" content="{% block summary %}Welcome to feyton Inc{% endblock summary %}" /> <!-- description shown in the actual shared post -->
    <meta property="og:image" content="/static/img/" /> <!-- image link, make sure it's jpg -->
    <meta property="og:url" content="https://www.feyton.co.rw/blog/" /> <!-- where do you want your post to link to -->
    <meta property="og:type" content="article" />

    <!-- Website Title -->
    <title>Feyton Inc - {% block title %}Blog{% endblock title %}</title>

    <!-- Styles -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,600,700,700i&amp;subset=latin-ext"
        rel="stylesheet">
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/fontawesome-all.css" rel="stylesheet">
    <link href="/static/css/swiper.css" rel="stylesheet">
    <link href="/static/css/magnific-popup.css" rel="stylesheet">
    <link href="/static/css/styles.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/forestry.css" class="css">

    <!-- Favicon  -->
    <link rel="icon" href="/static/img/favicon.png">
</head>

{% block body %}

<body data-spy="scroll" data-target=".fixed-top">
{% endblock body %}
    <!-- Preloader -->
    <div class="spinner-wrapper d-none">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
    <!-- end of preloader -->
{% include 'include/nav.html' %}

    <!-- Navigation -->



{% block content %}
{% endblock content %}

{% include 'include/footer.html' %}
{% include 'include/js.html' %}

templates/blog/blog.html
{% extends 'blog/base.html' %}

{% block desc %}Blog
{% endblock desc %}
{% block summary %}read and learn with us. Get access to trending news in tech and development.{% endblock summary %}

<body data-spy="scroll" data-target=".fixed-top">

    <!-- Preloader -->
    <div class="spinner-wrapper d-none">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
    <!-- end of preloader -->

    <!-- Navigation -->


    {% block content %}


    <!-- Header -->
    <header id="header" class="ex-header">
        <div class="header-content">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <div class="text-container">
                            <h2 class="text-left"><span class="turquoise">We are glad you are</span> HERE</h2>
                            <p class="p-large text-left">We talk tech, we provide solutions, we interact with our
                                reader.
                                <strong><span class="turquoise">We have what you are looking for.</span></strong> Or you
                                can request content. Even better, become an <span
                                    class="turquoise font-weight-bolder">author</span> yourself!</p>
                            <ul class="list-unstyled li-space-lg text-left pl-2">
                                {% for cat in categories %}
                                <li> <i class="fas fa-check"></i>&nbsp;{{cat.title}}</li>

                                {% endfor %}

                            </ul>
                            <a href="#" class="btn btn-info btn-outline" data-target="modal" data-toggle="modal">Request
                                Content</a> or <a href="#" class="btn btn-success btn-outline">BECOME AUTHOR</a>
                        </div> <!-- end of text-container -->
                    </div> <!-- end of col -->
                    <div class="col-lg-6">
                        <h2>Trending Posts</h2>

                        <!-- Card Slider -->
                        <div class="slider-container">
                            <div class="swiper-container card-slider">
                                <div class="swiper-wrapper">

                                    <!-- Slide -->
                                    {% for post in posts %}
                                    <div class="swiper-slide">
                                        <div class="card card-carousel">
                                            {% if post.thumbnail %}
                                            <img class="card-image image-link" src="{{post.thumbnail.url}}" alt="alternative" data-url="{{post.get_absolute_url}}">
                                            {% else %}
                                            <img class="card-image image-link" src="/static/img/post.jpg" alt="alternative" data-url="{{post.get_absolute_url}}">
                                            {% endif %}
                                            <div class="card-body">
                                                <p class="testimonial-text">{{post.summary|truncatechars:100}} <span class="text-info"><a href="{{post.get_absolute_url}}" class="link link-move link-success">Read more</a></span></p>
                                                <p class="testimonial-author">By: {{post.author.get_full_name}}</p>
                                            </div>
                                        </div>
                                    </div> <!-- end of swiper-slide -->
                                    {% endfor %}
                                    <!-- end of slide -->


                                </div> <!-- end of swiper-wrapper -->

                                <!-- Add Arrows -->
                                <div class="swiper-button-next"></div>
                                <div class="swiper-button-prev"></div>
                                <!-- end of add arrows -->

                            </div> <!-- end of swiper-container -->
                        </div> <!-- end of slider-container -->
                        <!-- end of card slider -->

                    </div>
                </div> <!-- end of row -->
            </div> <!-- end of container -->
        </div> <!-- end of header-content -->
    </header> <!-- end of header -->
    <!-- end of header -->



    <!-- About -->
    <div id="about" class="basic-4">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Latest Blogs</h2>
                    <p class="p-heading p-large"></p>
                </div> <!-- end of col -->

            </div> <!-- end of row -->
            <div class="row ">
                <div class="col-xg-8 col-md-8 col-sm-12">
                    <div class="card overflow-scroll h-500">
                        <div class="news_container">
                            <!-- News Post -->
                            {% for post in posts %}
                            <div
                                class="news_post d-flex flex-md-row flex-column align-items-start justify-content-start">
                                <div class="news_post_image">

                                    <img src="/static/img/post.jpg" alt=""
                                        height="200px" width="300px" class="rounded image-link"
                                        data-url="{{post.get_absolute_url}}" />
                                </div>

                                <div class="news_post_content text-left ml-1">
                                    <div class="news_post_title title-link">
                                        <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                                    </div>

                                    <div class="news_post_text text-left">
                                        <p>{{post.summary|safe}}</p>
                                    </div>
                                    <div class="button-group">
                                        <a href="{{post.get_absolute_url}}" class="btn btn-info pull-right btn-sm">Read
                                            More</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}



                        </div>
                    </div>
                </div>

                <!-- News Sidebar -->
                <div class="col-xl-4 col-md-4 col-sm-12">
                    <div class="card category mt-1">
                        <div class="card-header">
                            <h3>Categories</h3>
                        </div>
                        <div class="card-body">
                            <ul class="list-unstyled">
                                {% for cat in categories %}
                                <li class="media">
                                    <div class="media-body text-left">
                                        <a href="{{cat.get_absolute_url}}" class='n-decoration n-hover'>
                                            <i class="fa fa-arrow-alt-circle-right"></i>&nbsp;{{cat.title}} (#
                                            {{cat.posts.count}})
                                        </a>
                                    </div>


                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="card category mt-1">
                        <div class="card-header">
                            <h3>Popular Tags</h3>
                        </div>
                        <div class="card-body">
                            <ul class="list-unstyled text-left">
                                {% for t in tags %}
                                <li class="media">

                                    <div class="media-body"><a href="{{t.get_absolute_url}}"
                                            class="n-decocartion n-hover link-move bold link-info"><span
                                                class="turquoise">#</span> {{t.name}}</a></div>
                                    <i class="fas fa-check"> {{t.posts.count}}</i>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div> <!-- end of container -->
    </div> <!-- end of basic-4 -->
    <!-- end of about -->

    {% endblock content %}

templates/blog/create.html
{% extends 'blog/base.html' %}


{% block content %}

<form action="." method="post">
{{form.as_p}}
</form>

{% endblock content %}

templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}


<!-- Website Title -->
{% block title %}
{{post.title}}
{% endblock title %}

{% block desc %} {{title}}
{% endblock desc %}
{% block summary %} {{post.summary}}
{% endblock summary %}

{% block body %}

<body data-spy="scroll" data-target=".fixed-top" style="background-image: url('/static/images/header-background.jpg') ;"
    class="blog-body">
    {% endblock body %}

    {% block content %}

    <!-- About -->
    <div id="about" class="basic-3 mt-4">
        <div class="container">
            <div class="row ">
                <div class="col-xg-8 col-md-8 col-sm-12 ">
                    <div class="card post-view">
                        <div class="card-header">
                            <h2 class=" ">{{post.title}}</h2>
                        </div>
                        <div class="card-body text-left">
                            <div class="card-post text-left">
                                {{post.content|safe}}

                            </div>
                            <div class="button-group ">
                                <a href="" class="btn btn-outline-primary float-left mb-2 mt-4">Another post</a>
                                <a href="" class="btn btn-outline-success float-right mb-2 mt-4">Another one</a>
                            </div>
                            <div class="author ">
                                <div class="author-image col-md-4 col-sm-4">

                                    <img src="/static/img/favicon.png" alt="author image" height="150" width="150">
                                    <h3 class="name"><a href="#author">{{post.author.get_short_name}}</a> </h3>
                                </div>
                                <div class="info col-md-8 col-sm-8">
                                    <div class="row">

                                        <p class="bio">{{post.author.profile.biography}}</p>
                                    </div>
                                    <b>Follow me:</b>
                                    <ul class="social-author row">
                                        <li><a href="https://wa.me/{{ blog_post.author.telephone|safe}}"
                                                target="_blank"><i class="fab fa-whatsapp"></i>&nbsp;WhatsApp</a>
                                        </li>

                                        <li><a href="https://{{ blog_post.author.facebook|safe}}" target="_blank"><i
                                                    class="fab fa-facebook"></i>&nbsp;Facebook</a></li>

                                        <li><a href="https://{{ blog_post.author.twitter}}" target="_blank"><i
                                                    class="fab fa-twitter" aria-hidden="true"></i>&nbsp;Twitter</a>
                                        </li>

                                    </ul>

                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="comment-box text-center mt-2">
                        <a class="btn-solid-reg popup-with-move-anim" href="#details-lightbox-2">ADD/ VIEW COMMENTS</a>
                    </div>
                </div>

                <!-- News Sidebar -->
                <div class="col-xl-4 col-md-4 col-sm-12 ">
                    <div class="card">
                        <div class="card-header text-underline">
                            <h3>Post Stats</h3>
                        </div>
                        <div class="card-body">
                            <ul class="list-unstyled stats">
                                <li>Visits: <span>1000</span></li>
                                <li>Comments: <span>{{post.comments.count}}</span></li>
                                {% comment %} <li>Shares: </li> {% endcomment %}
                                <li>Category: <span><a href="{{post.category.get_absolute_url}}"
                                            class="link link-move link-success-sm capitalize">{{post.category}}</a></span>
                                </li>
                                <li>Tags:
                                    <ul class="capitalize">
                                        {% for tag in post.tags.all %}
                                        <li><a href="{{tag.get_absolute_url}}"
                                                class="link link-move link-info">{{tag.name}}</a></li>
                                        {% endfor %}

                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="card mt-2">
                        <div class="card-header">
                            <h3>You can read also</h3>
                        </div>
                        <div class="card-body">
                            <!-- start single post -->
                            {% for post in posts %}
                            <div class="row border-bottom p-1">
                                <div class="col-sm-3 overflow-hidden ">
                                    <img src="/static/img/post.jpg" alt="" height="50px" width="100%">
                                </div>
                                <div class="col-sm-9 ">
                                    <a href="{{post.get_absolute_url}}"
                                        class="link link-move link-success wrap bold v-center">{{post.title}}</a>
                                </div>
                            </div>
                            {% endfor %}
                            <!-- End single post -->
                        </div>
                    </div>
                    <div class="card category mt-1">
                        <div class="card-header">
                            <h3>Categories</h3>
                        </div>
                        <div class="card-body">
                            <ul class="list-unstyled">
                                {% for cat in categories %}
                                <li class="media">
                                    <div class="media-body"><a href="{{cat.get_absolute_url}}"
                                            class="n-decocartion n-hover link-move bold link-info">{{cat.title}}</a>
                                    </div>
                                    <i class="fas fa-check">&nbsp;({{cat.posts.count}})</i>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div> <!-- end of container -->
    </div> <!-- end of basic-4 -->
    <!-- end of about -->

    <!-- News -->
    <div id="details-lightbox-2" class="lightbox-basic zoom-anim-dialog mfp-hide">
        <div class="container">
            <div class="row">
                <button title="Close (Esc)" type="button" class="mfp-close x-button">×</button>
                <div class="col-lg-8">
                    <div class="text-container">
                        <h2>Comments</h2>
                        <div class="comments-list overflow-scroll">
                            <ul class=" list-unstyled">
                                {% for comment in post.comments.all %}
                                <li class="threaded-comments">
                                    <div class="comments-details">
                                        <div class="comments-list-img rounded">
                                            <div class="row">
                                                <img src="/static/img/b02.jpg" alt="post-author">
                                            </div>
                                            <div class="row">
                                                <b>{{comment.name}}</b>
                                            </div>

                                        </div>
                                        <div class="comments-content-wrap">
                                            <span>
                                                <b>Posted: </b>
                                                <span class="post-time">{{comment.created_on}} </span>
                                            </span>
                                            <p>{{comment.body}}
                                            </p>
                                        </div>
                                    </div>
                                </li>
                                {%empty%}
                                <p>Be the first to comment</p>
                                {% endfor %}

                            </ul>
                        </div>

                    </div> <!-- end of text-container -->
                </div> <!-- end of col -->
                <div class="col-lg-4">
                    <!-- Request Form -->
                    <div class="form-container">
                        <h5>Leave a comment</h5>
                        <p>Your email will not be published</p>
                        <form method='post' action='.'>
                            {% csrf_token %}

                            <div class="form-group">
                                <input type="text" class="form-control-input" id="id_name" name="name" required>
                                <label class="label-control" for="id_name">Full name</label>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control-input" id="id_email" name="email" required>
                                <label class="label-control" for="id_email">Email</label>

                            </div>

                            <div class="form-group">
                                <textarea name="body" class="form-control-input" id="" cols="30" rows="3"></textarea>
                                <label for="id_body" class="label-control">Comment</label>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group checkbox">
                                <input type="checkbox" id="rterms" value="Agreed-to-Terms" name="rterms" required>I
                                agree with Feyton Inc's stated <a href="{% url 'privacy' %}">Privacy Policy</a> and <a
                                    href="{% url 'terms' %}">Terms & Conditions</a>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="form-control-submit-button">LEAVE COMMENT</button>
                            </div>
                            <div class="form-message">
                                <div id="rmsgSubmit" class="h3 text-center hidden"></div>
                            </div>
                        </form>
                    </div> <!-- end of form-container -->
                    <!-- end of request form -->


                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </div> <!-- end of lightbox-basic -->



    {% endblock content %}